# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Egor Tolstoy

description: Stylish Jekyll Theme
author:
  name: Egor Tolstoy
  email: igrekde@gmail.com
  github: etolstoy
  twitter: igrekde
  linkedin: etolstoy
  bio: Team Lead @ Rambler&Co

rss_path: feed.xml
categories_path: categories.html

BASE_PATH:
